worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    # MIME types
    include mime.types;
    default_type application/octet-stream;
    types_hash_max_size 2048;

    # Security
    server_tokens off;
    proxy_hide_header X-Powered-By;
    fastcgi_hide_header X-Powered-By;

    # Performance
    keepalive_timeout 65;
    reset_timedout_connection on;

    # Client body
    client_max_body_size 50m;
    client_body_buffer_size 128k;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp_path;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    # Logging
    log_format main_timed
        # Standard (Combined format. Do not change this)
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
        # Custom extensions
        '$http_x_forwarded_for $request_time $upstream_response_time';

    # Suppress logging for healthcheck
    map $request_uri $loggable {
        /up 0;
        default 1;
    }

    access_log /dev/stdout main_timed if=$loggable;

    # Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_disable "msie6";
    gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/xhtml+xml
        application/xml
        font/eot
        font/otf
        font/ttf
        image/svg+xml
        text/css
        text/javascript
        text/plain
        text/xml;

    # Server configs
    include /etc/nginx/conf.d/*.conf;
}
