server {
    include /etc/nginx/server-common.conf;

    # Send all requests to Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass to PHP-FPM
    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/tmp/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Security: deny direct access to other PHP files
    location ~ \.php$ {
        return 404;
    }
}
